package com.JavaBackEnd.spring_boot_journey_week3_day2;

import com.JavaBackEnd.spring_boot_journey_week3_day2.entity.Task;
import com.JavaBackEnd.spring_boot_journey_week3_day2.entity.TaskPriority;
import com.JavaBackEnd.spring_boot_journey_week3_day2.entity.TaskStatus;
import com.JavaBackEnd.spring_boot_journey_week3_day2.entity.User;
import com.JavaBackEnd.spring_boot_journey_week3_day2.entity.UserRole;
import jakarta.persistence.EntityManager;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;

import java.time.LocalDate;
import java.time.LocalDateTime;

@SpringBootApplication
public class SpringBootJourneyWeek3Day2Application {

    public static void main(String[] args) {
        ApplicationContext context = SpringApplication.run(SpringBootJourneyWeek3Day2Application.class, args);

        System.out.println("\n✅ Application Started Successfully!");
        System.out.println("📊 Beans: " + context.getBeanDefinitionCount());
        System.out.println("\n📋 Tables created:");
        System.out.println("  - tasks");
        System.out.println("  - users");
    }

    @Bean
    public CommandLineRunner verifyEntityMapping(EntityManager entityManager) {
        return args -> {
            System.out.println("\n🔍 Verifying Entity Mapping...");

            // Check Task count
            Long taskCount = entityManager
                    .createQuery("SELECT COUNT(t) FROM Task t", Long.class)
                    .getSingleResult();
            System.out.println("  ✅ Tasks table exists. Count: " + taskCount);

            // Check User count
            Long userCount = entityManager
                    .createQuery("SELECT COUNT(u) FROM User u", Long.class)
                    .getSingleResult();
            System.out.println("  ✅ Users table exists. Count: " + userCount);

            System.out.println("\n✅ All entities mapped successfully!");
            System.out.println("📋 Check the console for SQL generated by Hibernate.");
        };
    }
}